In [35]:
import torch
import torch.nn as nn
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [36]:
#torch.stack

tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [37]:
#torch.multinomial

# define probability tensor
probabilities = torch.tensor([0.1,0.9]) # it assignes the index values to the tensor depending on the probability listed
# so in the tensor output there is a 10% change to get 0 (index ot 0.1) and 90% change of getting 1 (index of 90%)
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [38]:
#torch.tril

# trill stands for trangle lower

out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [39]:
output = torch.triu(torch.ones(5,5))
output

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [40]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf')) # basically takes the number and find e^that number
# so e^0 becomes 1 e^-inf becomes 0 .... referred to as exponentiation
print("out - ", out)
out2 = torch.exp(out)
print("Out exp - ", out2)

out -  tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])
Out exp -  tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [41]:
#torch.input.T / torch.input.transpose
input = torch.zeros(2,3,4)
out  = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [42]:
#torch.nn.linear

sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias = False)
print(linear(sample))

tensor([-7.1129,  6.7616, -7.4568], grad_fn=<SqueezeBackward4>)


In [43]:
#torch.cat
# short for concatenate

tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [44]:
#torch.F.softmax
import torch.nn.functional as F
#create a tensor
tensor1 = torch.tensor([1. , 2. , 3.])

softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [45]:
# Embedding

# initialize embedding layer
vocab_size = 1000
embedding_dim = 100

embedding = nn.Embedding(vocab_size, embedding_dim)

# create input token indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# apply embedding layer
embedded_output = embedding(input_indices)

# output shape
print(embedded_output.shape)

torch.Size([4, 100])


In [46]:
a = torch.tensor([[1,2],[3,4],[4,5]])
b = torch.tensor([[7,8,9], [10,11,12]])
print(a @ b)

tensor([[27, 30, 33],
        [61, 68, 75],
        [78, 87, 96]])


In [49]:
int_64 = torch.randint(1,(3,2))
float_32 = torch.rand(2,3)
# result = int_64 @ float_32  wont work because different datatypes

# result = torch.matmul(int_64, float_32)
# print(result) THis will still give you error
new_set = int_64.float()
# Now we have type casted
result = torch.matmul(new_set, float_32)
print(result) 

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
